apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 16.5.0
    digest: sha256:41c087eabcd1e7f0e3a879e5be718f889d0a22af6d24e806d61f784958dfebb6
  url: oci://ghcr.io/open-webui/helm-charts/open-webui
  # https://github.com/open-webui/helm-charts/pkgs/container/helm-charts%2Fopen-webui
