apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 16.6.0
    digest: sha256:c9946e8b62b02fc78b2ba9f7e80ebe112a60c8a08b14ffdd0e99a8c4ec9ff318
  url: oci://ghcr.io/open-webui/helm-charts/open-webui
  # https://github.com/open-webui/helm-charts/pkgs/container/helm-charts%2Fopen-webui
