apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.9.2
    digest: sha256:75c9e2ae8a3d98ac978118c82dec75db9c105cb079f2ba69022e52c9fc436527
  url: oci://ghcr.io/deliveryhero/helm-charts/node-local-dns
  # https://github.com/deliveryhero/helm-charts/pkgs/container/helm-charts%2Fnode-local-dns
