apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.19.3
    digest: sha256:0a22f95d56c30e5e9778bf887ba7e3e68b6570356c3d9de4921f3816edf098f5
  url: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
  # https://hub.docker.com/r/bitnamicharts/sealed-secrets/tags
