apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mlflow
  namespace: mlflow
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.17.0
    digest: sha256:8522ac6274e9ae70f45b4cb238cae42a12e5696000010fb0d5af9388d1042128
  url: oci://ghcr.io/mlflow/charts/mlflow
  # https://github.com/mlflow/mlflow/pkgs/container/charts%2Fmlflow
