apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: policy-controller
  namespace: sigstore-policy-controller
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.7
    digest: sha256:084ff7e27c7153750f4d8b7ed51bdd5fd2e366b435708e1119fb702c0d47c106
  url: oci://ghcr.io/sigstore/helm-charts/policy-controller
  # https://github.com/sigstore/helm-charts/pkgs/container/helm-charts%2Fpolicy-controller
