apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trivy-operator
  namespace: trivy
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.32.1
    digest: sha256:39caa565eaac9388bf5d86b9853e7535ae41703b4068475ea553c3e97754c06f
  url: oci://ghcr.io/aquasecurity/helm-charts/trivy-operator
  # https://github.com/aquasecurity/helm-charts/pkgs/container/helm-charts%2Ftrivy-operator
