apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubestellar
  namespace: kubestellar
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.30.0
    digest: sha256:29f9086a0f067ef614993702b31d4fe856d36269ab5e551b62ca69f8f2423bec
  url: oci://ghcr.io/kubestellar/kubestellar/core-chart
  # https://github.com/kubestellar/kubestellar/pkgs/container/kubestellar%2Fcore-chart
