apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gadget
  namespace: inspektor-gadget
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.56.1
    digest: sha256:9d25b802717a6c5d11f722c76bd1f58a551525438b3a1ac750f5e108c0f3dafa
  url: oci://ghcr.io/inspektor-gadget/inspektor-gadget/charts/gadget
  # https://github.com/inspektor-gadget/inspektor-gadget/pkgs/container/inspektor-gadget%2Fcharts%2Fgadget
