apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasti
  namespace: elasti
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: elasti
    namespace: flux-system
  values:
  # https://artifacthub.io/packages/helm/kubeelasti/elasti
  # https://github.com/KubeElasti/KubeElasti/blob/main/charts/elasti/values.yaml
    global:
      enableMonitoring: true
    