apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: contour
  namespace: contour
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 19.4.0
    digest: sha256:5db3aabf7691d6e40fc7f32aa3c6470d658b83b8f81331209edc1bd51292ff94
  url: oci://registry-1.docker.io/bitnamicharts/contour
  # https://hub.docker.com/r/bitnamicharts/contour/tags
