apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: contour
  namespace: contour
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 21.1.4
    digest: sha256:ff853d2dcce7978030e3db0c1a814c8239a689ded507e2aebeb64b8355ba32d9
  url: oci://registry-1.docker.io/bitnamicharts/contour
  # https://hub.docker.com/r/bitnamicharts/contour/tags
