apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openfga
  namespace: openfga
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.15
    digest: sha256:2e32a0d324ce8d64fdafe11abf36be5e4218464d30ce6e4e6a02e606fa73e53d
  url: oci://ghcr.io/openfga/helm-charts/openfga
  # https://github.com/openfga/helm-charts/pkgs/container/helm-charts%2Fopenfga
