apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: traefik
    namespace: traefik
  values:
  # https://artifacthub.io/packages/helm/traefik/traefik
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    metrics:
      prometheus:
        serviceMonitor:
          enabled: true
