apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 41.6.1
    digest: sha256:29ac8528d15084bef88c0369e1e678138466a3c880b4df399ee964359712e1db
  url: oci://ghcr.io/traefik/helm/traefik
  # https://github.com/traefik/helm/pkgs/container/helm%2Ftraefik
