apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: sidekick-output
  namespace: falco
spec:
  config:
    json_output: true
    stdout_output:
      enabled: true
    http_output:
      enabled: true
      url: "http://sidekick.falco.svc:2801"
  priority: 60
