apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: zot
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: zot
    namespace: zot
  values:
  # https://artifacthub.io/packages/helm/zot/zot
  # https://github.com/project-zot/helm-charts/blob/main/charts/zot/values.yaml
