apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: mend-renovate-ce
    namespace: renovate
  values:
  # https://artifacthub.io/packages/helm/renovate/renovate
  # https://github.com/mend/renovate-ce-ee/blob/main/helm-charts/mend-renovate-ce/values.yaml
