apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mend-renovate-ce
  namespace: renovate
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 15.6.0
    digest: sha256:2e43b6819c7da960935a6007d986f6bcfa3c4f6065218ceeca958d4eff31be8f
  url: oci://ghcr.io/mend/charts/mend-renovate-ce
  # https://github.com/mend/charts/pkgs/container/charts%2Fmend-renovate-ce
