apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mend-renovate-ce
  namespace: renovate
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 15.7.0
    digest: sha256:0dd4ad3a211dbb40e31e16fa12a081c59f85e5fe4a0716eea93751809318289b
  url: oci://ghcr.io/mend/charts/mend-renovate-ce
  # https://github.com/mend/charts/pkgs/container/charts%2Fmend-renovate-ce
