apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: llmkube
  namespace: llmkube
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.27
    digest: sha256:3ade90de1772711be94e1f7f178fbf411511c926876e64e62f0136c3bb62f57f
  url: oci://ghcr.io/defilantech/charts/llmkube
  # https://github.com/defilantech/llmkube/pkgs/container/charts%2Fllmkube
