apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-overprovisioner
  namespace: kube-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: cluster-overprovisioner
    namespace: kube-system
  values:
  # https://artifacthub.io/packages/helm/deliveryhero/cluster-overprovisioner
  # https://github.com/deliveryhero/helm-charts/blob/master/stable/cluster-overprovisioner/values.yaml
