apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cluster-overprovisioner
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.14
    digest: sha256:12fc8be9a4a9b1f507744231a688723f792a55ce6b9899cd00d57d9ec4c635c3
  url: oci://ghcr.io/deliveryhero/helm-charts/cluster-overprovisioner
  # https://github.com/deliveryhero/helm-charts/pkgs/container/helm-charts%2Fcluster-overprovisioner
