apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: falco-rules
  namespace: falco
spec:
  ociArtifact:
    image:
      repository: falcosecurity/rules/falco-rules
      tag: 5.2.0
    registry:
      name: ghcr.io
  priority: 50

# https://github.com/falcosecurity/rules/tree/main/rules