apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.2
    digest: sha256:06b607e662e27784bbbe73a0b3d5fc1a7f5d088414841fbfd893e739e57cae75
  url: oci://ghcr.io/external-secrets/charts/external-secrets
  # https://github.com/external-secrets/charts/pkgs/container/charts%2Fexternal-secrets
