apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flagger
  namespace: flagger
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.39.0
    digest: sha256:66e4059c52c3f088398717bb4fd0164336303abda15a8fb452743d072c318c29
  url: oci://ghcr.io/fluxcd/charts/flagger
  # https://github.com/fluxcd/charts/pkgs/container/charts%2Fflagger
