apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.1.0
    digest: sha256:27a901513e3fa8b210b4a06f08f90af288a2a2916b926a2a3118b285ca6fc3fc
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  # https://github.com/prometheus-community/charts/pkgs/container/charts%2Falertmanager
