apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.1
    digest: sha256:9c1c7e4bd1bc0c3fa786b2892ac0cf3a142d35acc5516f58ea8aa2f4b001b00f
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  # https://github.com/prometheus-community/charts/pkgs/container/charts%2Falertmanager
