apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.7.0
    digest: sha256:47193ebe7052f414c8c05ac2277b5b2b8fd62faf6f4f8ea6c7263a741e62acd7
  url: oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy
  # https://github.com/oauth2-proxy/charts/pkgs/container/charts%2Foauth2-proxy
