apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.7.1
    digest: sha256:38a52892fa72daf2b37b6eef249c3accd8accb372958de72d8ff199f48e70d80
  url: oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy
  # https://github.com/oauth2-proxy/charts/pkgs/container/charts%2Foauth2-proxy
