apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.4.4
    digest: sha256:50d7d0d1f8f37473f5e9675d1b4899f2f556ab375823c0798d6fdc428014c3e7
  url: oci://registry-1.docker.io/bitnamicharts/clickhouse
  # https://hub.docker.com/r/bitnamicharts/clickhouse/tags
