apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewarden
  namespace: kubewarden
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kubewarden-crds
    namespace: kubewarden
  upgrade:
    crds: CreateReplace
  values:
  # https://artifacthub.io/packages/helm/kubewarden/kubewarden-crds
  # https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-crds/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewarden
  namespace: kubewarden
spec:
  dependsOn:
  - name: kubewarden-crds
    namespace: kubewarden
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kubewarden-controller
    namespace: kubewarden
  values:
  # https://artifacthub.io/packages/helm/kubewarden/kubewarden-controller
  # https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/values.yaml
