apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubewarden-crds
  namespace: kubewarden
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.28.1
    digest: sha256:2857218cb5b050346398787a51cdcbbac71c063ba1c1ae504a764e9f9b61de10
  url: oci://ghcr.io/kubewarden/charts/kubewarden-crds
  # https://github.com/kubewarden/charts/pkgs/container/charts%2Fkubewarden-crds
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubewarden-controller
  namespace: kubewarden
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.14.1
    digest: sha256:472009ff479e60ab00b84a03dbd49a1f369104911e3b282d73856dad02b0845d
  url: oci://ghcr.io/kubewarden/charts/kubewarden-controller
  # https://github.com/kubewarden/charts/pkgs/container/charts%2Fkubewarden-controller
