apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubewarden-crds
  namespace: kubewarden
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.28.1
    digest: sha256:9097cde7b2f25f7d642286930085d028fd44502f4456eed19ff79ca808618ac3
  url: oci://ghcr.io/kubewarden/charts/kubewarden-crds
  # https://github.com/kubewarden/charts/pkgs/container/charts%2Fkubewarden-crds
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubewarden-controller
  namespace: kubewarden
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.14.1
    digest: sha256:84f78fc7c715b1340d6eaec92f83ff64c8130dd28fe132103e90aa17f8ac3bc6
  url: oci://ghcr.io/kubewarden/charts/kubewarden-controller
  # https://github.com/kubewarden/charts/pkgs/container/charts%2Fkubewarden-controller
