apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.4.6
    digest: sha256:69356bac304e283624184b0801a80c6cb330185e94a0794c701042d6a8a5df64
  url: oci://registry-1.docker.io/bitnamicharts/rabbitmq-cluster-operator
  # https://hub.docker.com/r/bitnamicharts/rabbitmq-cluster-operator/tags
