apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-password
  namespace: starrocks
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  data:
    - secretKey: password
      remoteRef:
        key: eks-data-dev
        property: starrocks-root-password
