apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: questdb
  namespace: questdb
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: questdb
    namespace: questdb
  values:
  # https://artifacthub.io/packages/helm/questdb/questdb
  # https://github.com/questdb/questdb-kubernetes/blob/master/charts/questdb/values.yaml
