apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k6-operator
  namespace: k6
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.0
    digest: sha256:dba46aec95678d255570896c8c0068f4793a12f42ad0e04c4381ad7e2e04aa8a
  url: oci://ghcr.io/grafana/helm-charts/k6-operator
  # https://github.com/grafana/helm-charts/pkgs/container/helm-charts%2Fk6-operator
