apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k6-operator
  namespace: k6
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.10.1
    digest: sha256:e73019c23a3121001d3161b087b26b903c735404103997b41fe51a06f0489cf5
  url: oci://ghcr.io/grafana/helm-charts/k6-operator
  # https://github.com/grafana/helm-charts/pkgs/container/helm-charts%2Fk6-operator
