# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host:8080
  config.vm.network "public_network", ip: "192.168.1.17"
  config.vm.synced_folder "./html", "/var/www/html"

  config.vm.provider 'virtualbox' do |vb|
    vb.name = "ubuntu-hello-world"
    vb.cpus = 1
    vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y nginx
  SHELL
end