apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-cd
  namespace: argocd
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.8.2
    digest: sha256:d892a98ab69114c328054f8fd43585a35933fb57bf187d50113710d7a592a3ce
  url: oci://ghcr.io/argoproj/argo-helm/argo-cd
  # https://github.com/argoproj/argo-helm/pkgs/container/argo-helm%2Fargo-cd
