apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: psmdb-operator
  namespace: percona-mongodb
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.23.2
    digest: sha256:667abf193ac4849f26ffaa2bda650ce0459c36fe725e4194fa388cfbdbd5bead
  url: oci://ghcr.io/percona/percona-helm-charts/psmdb-operator
  # https://github.com/percona/percona-helm-charts/pkgs/container/percona-helm-charts%2Fpsmdb-operator
