apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: authelia
  values:
  # https://artifacthub.io/packages/helm/authelia/authelia
  # https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
    ingress:
      enabled: true #... completar com o restante
    pod:
      kind: Deployment
    configMap:
      authentication_backend:
        file:
          enabled: true
      session:
        cookies:
        - subdomain: 'auth'
          domain: foobar.nip.io
      storage:
        local:
          enabled: true
      notifier:
        filesystem:
          enabled: true
      telemetry:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
