apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.15.1
    digest: sha256:ee7b5474b6f1fd83a730d1f0b246893ec1cdd2951524bffced129157c49bb3cd
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  # https://github.com/prometheus-community/helm-charts/pkgs/container/charts%2Fkube-prometheus-stack
