apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-ovn
  namespace: kube-ovn
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kube-ovn
    namespace: kube-ovn
  values:
  # https://github.com/kubeovn/kube-ovn/blob/master/charts/kube-ovn/values.yaml
