apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-ovn
  namespace: kube-ovn
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.16.10
    digest: sha256:7833ca0a8bb72e3254a5be9fa0f37b3f1b082d4b65ce5b96026718142501724c
  url: oci://ghcr.io/kubeovn/charts/kube-ovn
  # https://github.com/kubeovn/charts/pkgs/container/charts%2Fkube-ovn
