apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-ovn
  namespace: kube-ovn
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.16.7
    digest: sha256:dc563db488c8b251543bcc61865773bec9f8576b1668e23b3ccda11ada7d9728
  url: oci://ghcr.io/kubeovn/charts/kube-ovn
  # https://github.com/kubeovn/charts/pkgs/container/charts%2Fkube-ovn
