apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-ovn
  namespace: kube-ovn
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.16.4
    digest: sha256:39b5d8703e0b9cd890bac6a9d658789c3b749b012eeb6e962b0b4c82ecb6fbfd
  url: oci://ghcr.io/kubeovn/charts/kube-ovn
  # https://github.com/kubeovn/charts/pkgs/container/charts%2Fkube-ovn
