apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.5.31
    digest: sha256:4a0aff489dcb9dbf751d11c968de16ccd102edc117222a2b4352c71ecf832eaf
  url: oci://ghcr.io/opencost/charts/opencost
  # https://github.com/opencost/charts/pkgs/container/charts%2Fopencost
