apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: emissary-ingress
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: emissary-ingress
    namespace: emissary-ingress
  values:
  # https://artifacthub.io/packages/helm/datawire/emissary-ingress
  # https://github.com/emissary-ingress/emissary/blob/master/charts/emissary-ingress/values.yaml.in
    service:
      type: ClusterIP
