apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: capsule
    namespace: capsule
  values:
  # https://artifacthub.io/packages/helm/projectcapsule/capsule
  # https://github.com/projectcapsule/capsule/blob/main/charts/capsule/values.yaml
