apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capsule
  namespace: capsule
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.4
    digest: sha256:1da7a5742a2b30ed30e71832cf875becbc6a49551d020c940db52cf34045644e
  url: oci://ghcr.io/projectcapsule/charts/capsule
  # https://github.com/projectcapsule/charts/pkgs/container/charts%2Fcapsule
