apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capsule
  namespace: capsule
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.2
    digest: sha256:db11b9ee00802e6f8866ece40399fc557f1181b3bab78d41ffd20c0d1cd727c9
  url: oci://ghcr.io/projectcapsule/charts/capsule
  # https://github.com/projectcapsule/charts/pkgs/container/charts%2Fcapsule
