apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capsule
  namespace: capsule
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.14.5
    digest: sha256:1b82041b6e4e575a88accf9274cd772d56e67258ec0ea88059930fea895dab4b
  url: oci://ghcr.io/projectcapsule/charts/capsule
  # https://github.com/projectcapsule/charts/pkgs/container/charts%2Fcapsule
