apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: falco
  namespace: falco
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.1.0
    digest: sha256:a4e37213d1e97abc1290e026b79728facf1c1160b33935995d30be273ad17fd9
  url: oci://ghcr.io/falcosecurity/charts/falco
  # https://github.com/falcosecurity/charts/pkgs/container/charts%2Ffalco
