apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: falco
  namespace: falco
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.2.0
    digest: sha256:d6b24a89149bca25e92c67862106893b782d1dd1b92137e80ae76c2fd02f9421
  url: oci://ghcr.io/falcosecurity/charts/falco
  # https://github.com/falcosecurity/charts/pkgs/container/charts%2Ffalco
