apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: falco
  namespace: falco
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.21.3
    digest: sha256:c7a4d7c730fd8e462d0b7146de2a50137af53b7bd0faa60e8711bfa0e8b4a48c
  url: oci://ghcr.io/falcosecurity/charts/falco
  # https://github.com/falcosecurity/charts/pkgs/container/charts%2Ffalco
