apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langfuse
  namespace: langfuse
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: langfuse
    namespace: langfuse
  values:
  # https://artifacthub.io/packages/helm/langfuse-k8s/langfuse
  # https://github.com/langfuse/langfuse-k8s/blob/main/charts/langfuse/values.yaml
