apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: langfuse
  namespace: langfuse
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.1.0
    digest: sha256:22003a9056c3f12d0bcb36dd0000404a961383890818bbe4f615e39984f23ba9
  url: oci://ghcr.io/langfuse/langfuse-k8s/charts/langfuse
  # https://github.com/langfuse/langfuse-k8s/pkgs/container/langfuse-k8s%2Fcharts%2Flangfuse
