apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pyroscope
  namespace: pyroscope
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.3.1
    digest: sha256:9438372b83a45aa1731e470539fa24e98527ea31b62ba0072f396053a9612c09
  url: oci://ghcr.io/grafana/helm-charts/pyroscope
  # https://github.com/grafana/helm-charts/pkgs/container/helm-charts%2Fpyroscope
