apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pyroscope
  namespace: pyroscope
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.0
    digest: sha256:686f02f75ee02668830c0d8890a07e3f163c7aac869ab576fa52cf21da462b5e
  url: oci://ghcr.io/grafana/helm-charts/pyroscope
  # https://github.com/grafana/helm-charts/pkgs/container/helm-charts%2Fpyroscope
