{
 "title": "Kubernetes Node Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"} == 1\r\n  and ignoring(condition, status)\r\nkube_node_status_condition{condition=\"Ready\", status=\"true\"} == 1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"} == 1\r\n  and ignoring(condition, status)\r\nkube_node_status_condition{condition=\"Ready\", status=\"true\"} == 1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"PIDPressure\", status=\"true\"} == 1\r\n  and ignoring(condition, status)\r\nkube_node_status_condition{condition=\"Ready\", status=\"true\"} == 1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "All Conditions General",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition!~\"(Ready|VMEventScheduled)\", status=\"true\"} == 1\r\n  and ignoring(condition, status)\r\nkube_node_status_condition{condition=\"Ready\", status=\"true\"} == 1",
     "legendFormat": "{{node}}  |  {{condition}}"
    }
   ]
  }
 ]
}