{
 "title": "Kubernetes Pod Status",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Restarts Pods",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff Pods",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(time() - kube_pod_created) > 180\r\nand\r\nkube_pod_status_phase{phase=\"Pending\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ImagePullBackOff Pods",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=~\"ImagePullBackOff|ErrImagePull\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled Pods",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{reason=\"OOMKilled\", node!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttled Pods",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "(  rate(container_cpu_cfs_throttled_periods_total{container!=\"\",pod!=\"\"}[$__range])\r\n/  rate(container_cpu_cfs_periods_total{container!=\"\",pod!=\"\"}[$__range])\r\n) * 100 > 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exitcode Pods",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Pods",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Failed\"} * on(pod, namespace) group_left(reason) kube_pod_status_reason{reason=\"Evicted\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}