apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: jenkins
    namespace: jenkins
  values:
  # https://artifacthub.io/packages/helm/jenkinsci/jenkins
  # https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
