apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.9.56
    digest: sha256:462d0ace4e2dc1f10f8e15dac6a33949fb740bf5413d45a995a8dc9b46871b7e
  url: oci://ghcr.io/jenkinsci/helm-charts/jenkins
  # https://github.com/jenkinsci/helm-charts/pkgs/container/helm-charts%2Fjenkins
