apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.9.62
    digest: sha256:c8300ebbe5ec4adc5bae0eaaea493933b60550af6fb083abe4b242a72269da7b
  url: oci://ghcr.io/jenkinsci/helm-charts/jenkins
  # https://github.com/jenkinsci/helm-charts/pkgs/container/helm-charts%2Fjenkins
