apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.9.65
    digest: sha256:02d0a3c5b45c6935d34a72617b7390a280c59ab2105de59adf768f8d3e3b0f48
  url: oci://ghcr.io/jenkinsci/helm-charts/jenkins
  # https://github.com/jenkinsci/helm-charts/pkgs/container/helm-charts%2Fjenkins
