apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.7.0
    digest: sha256:1d91e6dcb9bb7a5d69ccfdddcd92f83548f520e82ba4edcdc91efe53d0a42f87
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
  # https://github.com/nginx/nginx-gateway-fabric/pkgs/container/charts%2Fnginx-gateway-fabric
