apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.4
    digest: sha256:c5c59025e673a75d2ef7c569675ae467f35e78e136f5e6641b9f1ffee84fe902
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  # https://github.com/kgateway-dev/kgateway/releases
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.4
    digest: sha256:ca19647e6bf097fc2d38499ae9d56a2273463b4c81aa46d18cbe908ebaa0206b
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  # https://github.com/kgateway-dev/kgateway/releases
