apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
  namespace: kgateway
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.5
    digest: sha256:d01a04c70387e8626843a35f831f5f01d5193e61668717e3852364f34c0b37cc
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  # https://github.com/kgateway-dev/kgateway/releases
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
  namespace: kgateway
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.5
    digest: sha256:98ccf8115b01fabab224cfb3fb88fd8b37b5f48c0738a04584aeb4c07d2776d7
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  # https://github.com/kgateway-dev/kgateway/releases
