apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aieg
  namespace: envoy-gateway
spec:
  dependsOn:
  - name: aieg-crd
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: aieg
    namespace: envoy-gateway
  values:
  # https://github.com/envoyproxy/ai-gateway/blob/main/manifests/charts/ai-gateway-helm/values.yaml
