apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: aieg
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.6.0
    digest: sha256:a273114eb7df12002196cb1c98c73ad63f66ca5349cc2e6cade3de0b0555e045
  url: oci://docker.io/envoyproxy/ai-gateway-helm
  # https://hub.docker.com/r/envoyproxy/ai-gateway-helm/tags
