apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: aieg
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.1.0
    digest: sha256:d599481cc8259a7d353207f140f16e40c31a39fca934e83013c89a6f5793269e
  url: oci://docker.io/envoyproxy/ai-gateway-helm
  # https://hub.docker.com/r/envoyproxy/ai-gateway-helm/tags
