apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: telepresence
  namespace: telepresence
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.32.2
    digest: sha256:45a027568276d9fe3c297ac534223f6210999b088bf36f04a252b58fcc321088
  url: oci://ghcr.io/telepresenceio/telepresence-oss
  # https://github.com/telepresenceio/telepresence/pkgs/container/telepresence-oss
