apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: telepresence
  namespace: telepresence
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.32.1
    digest: sha256:d9039a3dba3cd7c5f15e35423479e9346c399d6dfba0ff0d202fc4adc19c90de
  url: oci://ghcr.io/telepresenceio/telepresence-oss
  # https://github.com/telepresenceio/telepresence/pkgs/container/telepresence-oss
