apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.11.0
    digest: sha256:2e8e00d27dd88419974ed532a3b52714ce6017eb0a1e3abb1833fc24adb28c78
  url: oci://ghcr.io/kyverno/charts/policy-reporter
  # https://github.com/kyverno/charts/pkgs/container/charts%2Fpolicy-reporter
