apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.10.0
    digest: sha256:68488ecd283c2903666d5b335b8449923a55aaaaa84312993a8eca5fe650ff04
  url: oci://ghcr.io/kyverno/charts/policy-reporter
  # https://github.com/kyverno/charts/pkgs/container/charts%2Fpolicy-reporter
