apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-client
  namespace: tests2
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
