apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 15.0.6
    digest: sha256:20c4e681b0ce4cb8c7b2aee43f7d9f60217d445a2a23d4ed083ee6f687622b1d
  url: oci://registry-1.docker.io/bitnamicharts/rabbitmq
  # https://hub.docker.com/r/bitnamicharts/rabbitmq/tags
