apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 16.0.14
    digest: sha256:53769713d29cd8d9af4f1d3dfc9d02cc2fc9bd517c68bf65cefc6da99fb10f94
  url: oci://registry-1.docker.io/bitnamicharts/rabbitmq
  # https://hub.docker.com/r/bitnamicharts/rabbitmq/tags
