apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keydb
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.4
    digest: sha256:f0975d7e8d0105f1d24b3272c6996f2be79b789895df1abcb3f422221e6804c0
  url: oci://registry-1.docker.io/bitnamicharts/keydb
  # https://hub.docker.com/r/bitnamicharts/keydb/tags
