apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keydb
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.22
    digest: sha256:ab8a4b7afff5a07ea778bf9ee4a7b10a501867cc2cbd7199a068d6777d6e807f
  url: oci://registry-1.docker.io/bitnamicharts/keydb
  # https://hub.docker.com/r/bitnamicharts/keydb/tags
