apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubernetes-event-exporter
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.4.5
    digest: sha256:00ea329f2b139fe67e9f0f0692b4d58ac696b221b44d87179fc337d4c7362ef5
  url: oci://registry-1.docker.io/bitnamicharts/kubernetes-event-exporter
  # https://hub.docker.com/r/bitnamicharts/kubernetes-event-exporter/tags
