apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spire-crds
  namespace: spire
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.1
    digest: sha256:396ad05059251f6da27170696a5b01f7e649048dbac3c5b014c10e64a1ffd2cd
  url: oci://ghcr.io/spiffe/helm-charts/spire-crds
  # https://github.com/spiffe/helm-charts/pkgs/container/helm-charts%2Fspire-crds
