apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 10.4.0
    digest: sha256:7f0b8292b84492d79d4000d6848a238258e062feba3c828ce301b295ffa38532
  url: oci://ghcr.io/zitadel/zitadel-charts/zitadel
  # https://github.com/zitadel/zitadel-charts/pkgs/container/zitadel-charts%2Fzitadel
