apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: node-problem-detector
    namespace: kube-system
  values:
  # https://artifacthub.io/packages/helm/deliveryhero/node-problem-detector
  # https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/values.yaml
  # metrics:
  #   enabled: true
  #   serviceMonitor:
  #     enabled: true
