apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.1
    digest: sha256:7a1efb564acf4215a2fb6a5a076c4d5b0c649181c75d52c20a50db449e1932a4
  url: oci://ghcr.io/deliveryhero/helm-charts/node-problem-detector
  # https://github.com/deliveryhero/helm-charts/pkgs/container/helm-charts%2Fnode-problem-detector
