apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.3.1
    digest: sha256:d68a2d13046d8189ad9489b381c46c42da29c8a5632dd964a985b5aaf4770d4e
  url: oci://ghcr.io/codecentric/helm-charts/keycloakx
  # https://github.com/codecentric/helm-charts/pkgs/container/helm-charts%2Fkeycloakx
