apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litmus
  namespace: litmus
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.16.0
    digest: sha256:61df6452f627aa15abc4ced3ebd4a039b3d2a93a380aaaeb8265a203319d60a7
  url: oci://ghcr.io/litmuschaos/litmus-helm/litmus
  # https://github.com/litmuschaos/litmus-helm/pkgs/container/litmus-helm%2Flitmus
