apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litmus
  namespace: litmus
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.30.0
    digest: sha256:3bea5cf0772f6010d29163eb9466c6eaa0b2d208cc457cc52c2f3c0c0216441f
  url: oci://ghcr.io/litmuschaos/litmus-helm/litmus
  # https://github.com/litmuschaos/litmus-helm/pkgs/container/litmus-helm%2Flitmus
