apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: karpenter
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.14.3
    digest: sha256:bb73c90705b90a47205663d6ef8e2a56ff9eb118aa670a52b2f3ee12d511ddda
  url: oci://mcr.microsoft.com/aks/karpenter/karpenter
  # https://mcr.microsoft.com/en-us/artifact/mar/aks/karpenter/karpenter/tags
