apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: karpenter
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.14.2
    digest: sha256:bc0fc3cdd916e3b9e7b0528a3c3dc5e8bc8a61f455d7a6ac38ecb307499c566b
  url: oci://mcr.microsoft.com/aks/karpenter/karpenter
  # https://mcr.microsoft.com/en-us/artifact/mar/aks/karpenter/karpenter/tags
