apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
  namespace: dependency-track
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: dependency-track
    namespace: dependency-track
  values:
  # https://artifacthub.io/packages/helm/dependencytrack/dependency-track
  # https://github.com/DependencyTrack/helm-charts/blob/main/charts/dependency-track/values.yaml
