apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dependency-track
  namespace: dependency-track
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.5.0
    digest: sha256:1f0357eb4fbad780893e77325cd2d167fc961173dbc0497827c0de299311688c
  url: oci://ghcr.io/dependencytrack/helm-charts/dependency-track
  # https://github.com/dependencytrack/helm-charts/pkgs/container/helm-charts%2Fdependency-track
