apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dependency-track
  namespace: dependency-track
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.7.0
    digest: sha256:f348b858c0a3200eae64e212cb3671bd0ce3f065b8acbdce64568222f6184694
  url: oci://ghcr.io/dependencytrack/helm-charts/dependency-track
  # https://github.com/dependencytrack/helm-charts/pkgs/container/helm-charts%2Fdependency-track
