#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: openbao-init
#  namespace: openbao
#data:
#  openbao-init.sh: |
#    export BAO_TOKEN=root
#
#    echo "Waiting for OpenBao to be ready..."
#    until bao status >/dev/null 2>&1; do sleep 1; done
#
#    echo "Enabling KV secrets engine at path 'pikakube'..."
#    bao secrets enable -path=pikakube -version=2 kv || true
#
#    echo "Adding secrets..."
#    bao kv put pikakube/variables/hello value=world
#    bao kv put pikakube/variables/hello2 value=world2
#
#
#    echo "OpenBao initialization script completed."