apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openbao
  values:
  # https://artifacthub.io/packages/helm/openbao/openbao
  # https://github.com/openbao/openbao-helm/blob/main/charts/openbao/values.yaml
    server:
      dev:
        enabled: true
      ingress:
        enabled: true
        annotations:
          forecastle.stakater.com/expose: "true"
          #forecastle.stakater.com/icon: "https://icon.icepanel.io/Technology/svg/HashiCorp-Vault.svg"
          forecastle.stakater.com/appName: "OpenBao"
          forecastle.stakater.com/group: "Security"
        hosts:
        - host: openbao.127.0.0.1.nip.io
          paths: 
          - /
        tls:
        - secretName: mkcert-tls-secret
          hosts:
          - openbao.127.0.0.1.nip.io
