apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonflydb
  namespace: dragonflydb
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.0.0
    digest: sha256:637cafc6aaa044e2dbe8ac978f0f0dc5935f22e6b07722a91ddf69a797e2ead6
  url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
  # https://github.com/dragonflydb/dragonfly/pkgs/container/dragonfly%2Fhelm%2Fdragonfly
