apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: postgres-operator
    namespace: postgres-operator
  values:
  # https://artifacthub.io/packages/helm/postgres-operator/postgres-operator
  # https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/values.yaml
