apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: thanos
  namespace: thanos
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 17.3.1
    digest: sha256:7448f09945cd571774bea8dc10c73c24c28ce57d6eea1978420f6b396f863674
  url: oci://registry-1.docker.io/bitnamicharts/thanos
  # https://hub.docker.com/r/bitnamicharts/thanos/tags
