apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: argo-workflows
    namespace: argo-workflows
  values:
  # https://artifacthub.io/packages/helm/argo/argo-workflows
  # https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml
    crds:
      keep: false
    secure: true
