apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.11
    digest: sha256:93f2dfcbf8d12e01e2ddc347535167fffe029be2bf229c86fefae28a9045b8fc
  url: oci://ghcr.io/argoproj/argo-helm/argo-workflows
  # https://github.com/argoproj/argo-helm/pkgs/container/argo-helm%2Fargo-workflows
