apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.6
    digest: sha256:bc0a67c690f858ead28b037d8c2e49ef9defc08dadcbf67ee76c62af77fd3389
  url: oci://ghcr.io/argoproj/argo-helm/argo-workflows
  # https://github.com/argoproj/argo-helm/pkgs/container/argo-helm%2Fargo-workflows
