apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.0.4
    digest: sha256:c1993716605ab6cf8d43a79ec870cdda0a16f4857080d57243564a9a1f384dfd
  url: oci://ghcr.io/argoproj/argo-helm/argo-workflows
  # https://github.com/argoproj/argo-helm/pkgs/container/argo-helm%2Fargo-workflows
