apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: openebs
    namespace: openebs
  values:
  # https://artifacthub.io/packages/helm/openebs/openebs
  # https://github.com/openebs/openebs/blob/main/charts/values.yaml
