apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: redis
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 28.1.0
    digest: sha256:795df3b4dda22a86db62f511a62970fb547658b0d1349ec210783516b2e6157e
  url: oci://registry-1.docker.io/bitnamicharts/redis
  # https://hub.docker.com/r/bitnamicharts/redis/tags
