apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.7.1
    digest: sha256:5552a18d903098bbdaa8e2b459343fe57a4985053c484cdc2a28163c1f5799ba
  url: oci://ghcr.io/nginx/charts/nginx-ingress
  # https://github.com/nginx/kubernetes-ingress/pkgs/container/charts%2Fnginx-ingress
