apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.24.0
    digest: sha256:ff0efc0f683bfccab5cbc8fd7959dab417f13dbbcf2a713199ff9f43f0d0bed3
  url: oci://ghcr.io/bank-vaults/helm-charts/vault-operator
  # https://github.com/bank-vaults/vault-operator/pkgs/container/helm-charts%2Fvault-operator
