apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vault-operator
  namespace: vault-operator
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.24.1
    digest: sha256:98ed8dc00d0eb8e06f5ef640fd32b84fb5e6bf94b0878878148299456fe1c80c
  url: oci://ghcr.io/bank-vaults/helm-charts/vault-operator
  # https://github.com/bank-vaults/vault-operator/pkgs/container/helm-charts%2Fvault-operator
