graph TD
    subgraph AirflowNamespace[Airflow Namespace]
        subgraph AirflowCore[Airflow Core]
            DAGProcessor[DAG Processor]
            Scheduler[Scheduler]
            APIServer[API Server]
        end

        StatsD[StatsD]
        PostgresDB[Postgres Metadata DB]

        subgraph EFS[Shared EFS Volumes]
            EFS_DAGs[EFS DAGs]
            EFS_Logs[EFS Logs <br/><b>TTL: 15 Days</b>]
            
        end

        subgraph Configurations[Configurations]
            ConfigMap[ConfigMap]
            Secrets[Secrets]
        end
    end

    Users[Users]

    subgraph Ingress[Ingress]
        Nginx
    end

    %% Conexões Core com Infra
    AirflowCore --> EFS
    AirflowCore -- "push metrics" --> StatsD
    AirflowCore --> PostgresDB
    AirflowCore --> Configurations
    Users -- "only VPN" --> Nginx
    Nginx -- "SSO" --> APIServer
    %% GitHub Repository e Actions
    subgraph GitHub[Project GitHub Repository]
        DAG[DAG Code]
        subgraph GitHubActions[GitHub Actions]
            WorkflowDeployDAG[Deploy DAG]
            WorkflowBuildImage[Build Image]
        end
        DAG -- "Commit" --> WorkflowDeployDAG
        subgraph DockerfileProject[Dockerfile]
            ImageBase[Base Image]
            project-deps[Project Dependencies]
        end

        DockerfileProject -- "tag"--> WorkflowBuildImage
    end

    subgraph AirflowImage[Airflow Image GitHub Repository]
        subgraph Dockerfile
            airflow-providers
            dbt-adapters
        end
        subgraph GA[GitHub Actions]
            WorkflowBuildBaseImage[Build Image]
        end

        Dockerfile -- "tag"--> GA
    end

    %% Conexão com texto solicitado
    WorkflowDeployDAG -- "copy code" --> EFS_DAGs

    %% Namespace do projeto
    subgraph ProjectNamespace[Project Namespace]
        Worker[Worker Pod]

        subgraph ProjectEFS[Shared EFS Volumes]
            ProjectEFS_DAGs[EFS DAGs]
            ProjectEFS_Logs[EFS Logs]
        end

        subgraph ProjectConfigurations[Configurations]
            ProjectConfigMap[ConfigMap]
            ProjectSecrets[Secrets]
        end
    end

    Worker --> Scheduler

    %% AWS bloco separado com IAM Role
    subgraph AWS[AWS]
        IAMRole[IAM Role]
        SecretsManager[SecretsManager]
        Snapshot[PVC Snapshot]
        EFSBackup[EFS Backup] 
        subgraph ECR[ECR]
            BaseImage[Airflow Image]
            ProjectImage[Project Image]
        end
    end

    GA --> BaseImage
    BaseImage --> AirflowCore
    ImageBase --> BaseImage
    WorkflowBuildImage -- "build"--> ProjectImage
    Worker --> IAMRole
    Worker --> ProjectImage
    Worker --> ProjectEFS
    Worker --> ProjectConfigurations

    AirflowCore -- "Vars & Conns" --> SecretsManager
    PostgresDB -- "Backup" --> Snapshot
    EFS_DAGs --> EFSBackup

    %% Kyverno
    Kyverno[Kyverno]
    EFS --> Kyverno
    Configurations --> Kyverno
    ProjectEFS -- "namespace label \n airflow: true" --> Kyverno
    ProjectConfigurations -- "namespace label \n airflow: true" --> Kyverno

    subgraph Monitoring[Monitoring]
        Prometheus
    end

    StatsD -- "collect metrics" --> Prometheus