graph TD
    User[Users] -->|create and update secrets | ASM

    subgraph AWS [AWS]
        ASM[AWS Secrets Manager]
    end

    ASM -- referenced by --> ClusterSecretStore
    
    subgraph Kubernetes [Kubernetes]
        direction TD      
        subgraph ESO_Resources [ESO Custom Resources]
            ClusterSecretStore[ClusterSecretStore]
            ExternalSecret[ExternalSecret]

            ClusterSecretStore -- referenced by --> ExternalSecret
        end

        Secret[Secret]
        Pods[Pods]
    end

    ExternalSecret -- syncs --> Secret
    Secret -- used by --> Pods
