graph TD
    subgraph GitHub_App[Application GitHub Repository]
        Caller[Caller Workflow]
    end

    subgraph GitHub_DataOps[dataops-actions GitHub Repository]
        Reusable[Reusables Workflows<br/>- deploy-dags<br/>- build-docker-image<br/>- terraform]
        Dockerfile[Dockerfile<br/>with workflow dependencies]
    end

    subgraph Update
        Releases[Releases actions/runner] -- when --> Dockerfile
    end

    subgraph Container Registry
        Image[Docker Image]
    end

    subgraph Kubernetes
        ARC[Actions Runner Controller]
        ScaleSet[Runner Scale Set]
        Listener[Listener]
        Pods[Ephemeral Pods Runners]

        ARC --> ScaleSet
        ScaleSet --> Listener
        Listener --> Pods
    end

    subgraph Internal Resources
        APIs[APIs]
        DBs[Databases]
        Airflow[Airflow]
        AWS[AWS]
    end

    %% Conexões entre os blocos
    Caller -- uses --> Reusable
    
    Reusable --> ScaleSet
    
    Dockerfile -- repo tag build --> Image
    Image --> ScaleSet
    
    Pods --> APIs
    Pods --> DBs
    Pods --> Airflow
    Pods --> AWS
