apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 29.27.2
    digest: sha256:036172da52e7f4e657e4fe7a794df1f5e97af7dbb66bf671a5c257b150af1084
  url: oci://ghcr.io/prometheus-community/charts/prometheus
  # https://github.com/prometheus-community/charts/pkgs/container/charts%2Fprometheus
