apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 29.34.0
    digest: sha256:c26429777cfab8018ebb5d6c8d58578fb40b4f891701f02a672c7f82ed39b1b3
  url: oci://ghcr.io/prometheus-community/charts/prometheus
  # https://github.com/prometheus-community/charts/pkgs/container/charts%2Fprometheus
