apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis-operator
  namespace: redis
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.26.1
    digest: sha256:95d290f7263d06fd2af50c02738583db53eca05b6d1ad25b97e2695a21edaf3b
  url: oci://ghcr.io/ot-container-kit/charts/redis-operator
  # https://github.com/OT-CONTAINER-KIT/redis-operator/pkgs/container/charts%2Fredis-operator
