apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis-operator
  namespace: redis
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.26.1
    digest: sha256:fc0b32e677caee36324acb32c4572187e82a5a67c950a18a8bc4969a93bb24b8
  url: oci://ghcr.io/ot-container-kit/charts/redis-operator
  # https://github.com/OT-CONTAINER-KIT/redis-operator/pkgs/container/charts%2Fredis-operator
