apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: atlas-operator
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.48
    digest: sha256:15adc2fa0d7cc63387a008870fb6ef78390271ad6159ac16b1696e9543cf5ac0
  url: oci://ghcr.io/ariga/charts/atlas-operator
  # https://github.com/ariga/atlas-operator/pkgs/container/charts%2Fatlas-operator
