apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: atlas-operator
  namespace: atlas
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.8.0
    digest: sha256:3f9c194e58f04323bc91a0a3538b82882a3b66cd0dde9eedc195deba45188c62
  url: oci://ghcr.io/ariga/charts/atlas-operator
  # https://github.com/ariga/atlas-operator/pkgs/container/charts%2Fatlas-operator
