apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: atlas-operator
  namespace: atlas
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.7.51
    digest: sha256:3215dc932b000eaccb0d49878e968757c15bf1f4c384d9830c7d9bdebeef8168
  url: oci://ghcr.io/ariga/charts/atlas-operator
  # https://github.com/ariga/atlas-operator/pkgs/container/charts%2Fatlas-operator
