apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: retina
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.0.29
    digest: sha256:3e683f55c74c6666e436d3c0cb7df2b6cba854983c2b56454547083aed64d242
  url: oci://ghcr.io/microsoft/retina/charts/retina
  # https://github.com/microsoft/retina/pkgs/container/retina%2Fcharts%2Fretina
