apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: retina
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.2.8
    digest: sha256:d5251a5e1e6667d58ee3b74391214e725f8771875eb76008af65f66ff49765de
  url: oci://ghcr.io/microsoft/retina/charts/retina
  # https://github.com/microsoft/retina/pkgs/container/retina%2Fcharts%2Fretina
