apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-demo
  namespace: opentelemetry
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: opentelemetry-demo
    namespace: opentelemetry
  values:
  # https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-demo
  # https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/values.yaml
