apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-demo
  namespace: opentelemetry
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.42.1
    digest: sha256:ce366ac232dde9afceab2702b98e61a9f9df10ee8e4edc184d478b12b6ae84bd
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-demo
  # https://github.com/open-telemetry/opentelemetry-helm-charts/pkgs/container/opentelemetry-helm-charts%2Fopentelemetry-demo
