apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kargo
  namespace: kargo
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.12.1
    digest: sha256:bf152ea5087c340181ec8deabc8c8920957493ed3fd756f62e28a224ebdb0833
  url: oci://ghcr.io/akuity/kargo-charts/kargo
  # https://github.com/akuity/kargo-charts/pkgs/container/kargo-charts%2Fkargo
