apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kargo
  namespace: kargo
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.12.3
    digest: sha256:92139a2c3ab6075d9b9c5ce4a1a7e51d7b9592ceb078db4b6c3adcb2da32ac5e
  url: oci://ghcr.io/akuity/kargo-charts/kargo
  # https://github.com/akuity/kargo-charts/pkgs/container/kargo-charts%2Fkargo
