apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: aieg-crd
  namespace: flux-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.6.0
    digest: sha256:4c1812e15c24714726da1eeabbdc87e895d14f0dfb49e87aeff59d3462d89bb4
  url: oci://docker.io/envoyproxy/ai-gateway-crds-helm
  # https://hub.docker.com/r/envoyproxy/ai-gateway-crds-helm/tags
