apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis-cluster
  namespace: redis
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 13.0.4
    digest: sha256:45229772bdde004303e5eaf12c1fff839811ba7f17d63e9fc6cbd8923d0531c2
  url: oci://registry-1.docker.io/bitnamicharts/redis-cluster
  # https://hub.docker.com/r/bitnamicharts/redis-cluster/tags
