apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kueue
  namespace: kueue
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.19.4
    digest: sha256:a11f1ab76d9133d8ae7cbcfbd0ad6a5ee5cb4494831144ceef09688f6738dc9d
  url: oci://registry.k8s.io/kueue/charts/kueue
  # https://registry.k8s.io/v2/kueue/charts/kueue/tags/list
