apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kueue
  namespace: kueue
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.20.0
    digest: sha256:61857945f1109da052dcc01baf79ea912a6c2a5ffeb087f3dfe270c9ea198c9c
  url: oci://registry.k8s.io/kueue/charts/kueue
  # https://registry.k8s.io/v2/kueue/charts/kueue/tags/list
