apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.173.1
    digest: sha256:cc821c73ee08f031f6f9a6b3d041d662ee7a83ab12adf645c513ad153de2157e
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-collector
  # https://github.com/open-telemetry/opentelemetry-helm-charts/pkgs/container/opentelemetry-helm-charts%2Fopentelemetry-collector
