apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-app
  namespace: kagent
spec:
  refreshInterval: 168h
  target:
    name: postgres-app
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: pg-password-generator