apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.102.1
    digest: sha256:b2c57bc96452225d18a110daa5aecd444e314a54c8ed8d25dc60a16b315a1526
  url: oci://ghcr.io/berriai/litellm-helm
  # https://github.com/BerriAI/litellm/pkgs/container/litellm-helm
