apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.104.2
    digest: sha256:960e35a803da0d20efeb991a5f34847edcc21b1e8c645b749d84c8b664b42e4e
  url: oci://ghcr.io/berriai/litellm-helm
  # https://github.com/BerriAI/litellm/pkgs/container/litellm-helm
