apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.101.0
    digest: sha256:a3a9a8665377916a8dc721a7d0613413d8c7ed03075cf114573ea25a27111cfa
  url: oci://ghcr.io/berriai/litellm-helm
  # https://github.com/BerriAI/litellm/pkgs/container/litellm-helm
