apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: retina-hubble
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.2.8
    digest: sha256:fa6a800f611f80a9ad09b94bd52b566fc78c53d7fc53cefee6cf44235423e513
  url: oci://ghcr.io/microsoft/retina/charts/retina-hubble
  # https://github.com/microsoft/retina/pkgs/container/retina%2Fcharts%2Fretina-hubble
