apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: retina-hubble
  namespace: kube-system
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.2.9
    digest: sha256:747b9aee20b4df391693635f2930b4ab78d7ef909f11ab01106afa51febfd34f
  url: oci://ghcr.io/microsoft/retina/charts/retina-hubble
  # https://github.com/microsoft/retina/pkgs/container/retina%2Fcharts%2Fretina-hubble
