apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway-crds
  namespace: kgateway
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.6
    digest: sha256:9308e5fb6608838b44e66b42ea44782082b952bcea873f49f9b63ae117b10abf
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
  # https://github.com/kgateway-dev/kgateway/releases
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kgateway
  namespace: kgateway
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v2.4.6
    digest: sha256:ef9840f9ed3ebc847d5484ee4b2de8df6f7ab7dbfc64a5eb1de315bdd9ca7762
  url: oci://cr.kgateway.dev/kgateway-dev/charts/kgateway
  # https://github.com/kgateway-dev/kgateway/releases
