apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: robusta
  namespace: robusta
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.50.0
    digest: sha256:494c8cf9bcab3c9674c5596f57e0141133aee7e51c5e823e84304db1134d4d36
  url: oci://ghcr.io/robusta-dev/charts/robusta
  # https://github.com/robusta-dev/charts/pkgs/container/charts%2Frobusta
