apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: robusta
  namespace: robusta
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.51.0
    digest: sha256:1450d422452c3a0294e83670c9670d7fc345e59356f50c0f755b017228c7f504
  url: oci://ghcr.io/robusta-dev/charts/robusta
  # https://github.com/robusta-dev/charts/pkgs/container/charts%2Frobusta
