apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy
  namespace: haproxy
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kubernetes-ingress
    namespace: haproxy
  values:
  # https://artifacthub.io/packages/helm/haproxytech/kubernetes-ingress
  # https://github.com/haproxytech/helm-charts/blob/main/kubernetes-ingress/values.yaml
