apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubernetes-ingress
  namespace: haproxy
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.54.2
    digest: sha256:daa725626d0bed39718cf6a1986f50527a6d9175e0fc472c81b04ddd8c26a948
  url: oci://ghcr.io/haproxytech/helm-charts/kubernetes-ingress
  # https://github.com/haproxytech/helm-charts/pkgs/container/helm-charts%2Fkubernetes-ingress
