apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kubernetes-ingress
  namespace: haproxy
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.54.0
    digest: sha256:59f1de715809193429d346a50e6d56a9a689d4fb38dbba859f9b2ea79f571a8e
  url: oci://ghcr.io/haproxytech/helm-charts/kubernetes-ingress
  # https://github.com/haproxytech/helm-charts/pkgs/container/helm-charts%2Fkubernetes-ingress
