apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.0.0
    digest: sha256:b3aae80a7b438ccd6bacdbde3453469bf2cc5d09ca26c1b8bf27847e70921e24
  url: oci://ghcr.io/grafana-community/helm-charts/tempo
  # https://github.com/grafana-community/helm-charts/pkgs/container/helm-charts%2Ftempo
