apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.1.0
    digest: sha256:cad53aac20f037073ec81fee8833d2a71edb550bcfbb75be22b37767dd6bd864
  url: oci://ghcr.io/grafana-community/helm-charts/tempo
  # https://github.com/grafana-community/helm-charts/pkgs/container/helm-charts%2Ftempo
