apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mimir-distributed
  namespace: mimir
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.2.1
    digest: sha256:a8a20ffe3b875a110f57d50fc089fabe494fd8147b04fe039c47edf343e2695b
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  # https://github.com/grafana/helm-charts/pkgs/container/helm-charts%2Fmimir-distributed
