apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coder
  namespace: coder
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.37.3
    digest: sha256:922fa45fae4cb2e2cb92d73fb0327878cc84177c3c701affa5cfb866706b4d50
  url: oci://ghcr.io/coder/chart/coder
  # https://github.com/coder/chart/pkgs/container/chart%2Fcoder
