apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-postgres-exporter
  namespace: prometheus
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.2.0
    digest: sha256:52f7a568d8f3e44e93f5837976aaf6a8ea6f3561ac9eb035bc4f12441557abd5
  url: oci://ghcr.io/prometheus-community/charts/prometheus-postgres-exporter
  # https://github.com/prometheus-community/charts/pkgs/container/charts%2Fprometheus-postgres-exporter
