apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  dependsOn:
  - name: prometheus-crds
  interval: 5m
  # wait for the HelmRelease to be Ready so dependsOn means the CRDs/pods exist
  wait: true
  timeout: 10m
  path: ./infrastructure/security/2-cluster/policies/kyverno
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-manifests
  namespace: flux-system
spec:
  dependsOn:
  - name: kyverno
  interval: 5m
  # wait for the HelmRelease to be Ready so dependsOn means the CRDs/pods exist
  wait: true
  timeout: 10m
  path: ./infrastructure/security/2-cluster/policies/kyverno/policies
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system