apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.10.2
    digest: sha256:e95965425936d58a666e0d860b431766570777d613dc5cae6dbb6e1629286786
  url: oci://ghcr.io/backstage/charts/backstage
  # https://github.com/backstage/charts/pkgs/container/charts%2Fbackstage
