apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.10.0
    digest: sha256:214ea94d18ee5612aec4a5b8ca610508c9e5891c7b9767d67d8e163c0ac35707
  url: oci://ghcr.io/backstage/charts/backstage
  # https://github.com/backstage/charts/pkgs/container/charts%2Fbackstage
