apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 18.1.0
    digest: sha256:76dec43dc7004225d170c52e931321d63f4b3dfef14b360fbedbc9f372a62417
  url: oci://registry-1.docker.io/bitnamicharts/phpmyadmin
  # https://hub.docker.com/r/bitnamicharts/phpmyadmin/tags
