apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 20.0.0
    digest: sha256:bbb868ade4e069027206babdd9a841ee933cf4912919a7d2e8206637f69b3878
  url: oci://registry-1.docker.io/bitnamicharts/phpmyadmin
  # https://hub.docker.com/r/bitnamicharts/phpmyadmin/tags
