apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: lws
  namespace: lws
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.11.1
    digest: sha256:bf492d6b8310ad8177531a35cd6b559d6ba6e7cb1fb31192d9f6a825c7f7c4ac
  url: oci://registry.k8s.io/lws/charts/lws
  # https://registry.k8s.io/v2/lws/charts/lws/tags/list
