apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mailpit
  namespace: mailpit
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.37.0
    digest: sha256:cf276965c456c5dc0746b4de3f50441bf580d29f70abeaca5ce09ea65a356c87
  url: oci://ghcr.io/jouve/charts/mailpit
  # https://github.com/jouve/charts/pkgs/container/charts%2Fmailpit
