apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openchoreo-control-plane
  namespace: openchoreo
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.3.0
    digest: sha256:62e615b63ba536d841f942c73542bfbad1da753a431a2012e21cc7d4e50f3c9f
  url: oci://ghcr.io/openchoreo/helm-charts/openchoreo-control-plane
  # https://github.com/openchoreo/openchoreo/pkgs/container/helm-charts%2Fopenchoreo-control-plane
