apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openchoreo-control-plane
  namespace: openchoreo
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.2.5
    digest: sha256:3b6e1ce244ffa7d89680855fd43dc79e40d28512fe1a7f86dbe9811078c844c4
  url: oci://ghcr.io/openchoreo/helm-charts/openchoreo-control-plane
  # https://github.com/openchoreo/openchoreo/pkgs/container/helm-charts%2Fopenchoreo-control-plane
