apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: oncall
  namespace: oncall
spec:
  interval: 24h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.16.5
    digest: sha256:651dd727052da3472ae56c97ce033dbdb69488980c768239bebb9f1cd5e14053
  url: oci://ghcr.io/grafana/helm-charts/oncall
  # https://github.com/orgs/grafana/packages/container/package/helm-charts%2Foncall
